# Generated by Django 3.2 on 2021-05-12 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('content', models.TextField(max_length=10000, verbose_name='Текст')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post.subject', verbose_name='Предмет')),
            ],
        ),
    ]
